source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'smebup' do
pod 'Gloss', '~> 0.6.2'
end


target 'smebupTests' do
    pod 'Quick', '~> 0.9.1'
    pod 'Nimble', '3.1.0'
end
